Corrected VEL3D-K DPA
oceanobservatories/ion-functions pull request #10
Opened 2018-06-20 22:14 UTC by desiderr

The Matlab code supplied by Nortek in 2014 for the VEL3D-K DPA had 3 errors.

The VEL3D-K DPA has been corrected using code sent by Nortek in 2017. A new unit test has been coded  and new unit test values have been added to replace erroneous values in previously written unit tests.

2018-09-12 16:21 UTC, cwingard approved these changes

2018-09-12 19:37 UTC, desiderr commented
Dan, could you review this pull request and merge if appropriate? This addresses redmine ticket 13461, which I authored.

2018-09-12 19:49 UTC, danmergens approved these changes
Brings me back to the days when I had to correct coordinate transform code; nice fix.

2018-09-12 19:50 UTC, danmergens requested changes
Please update the RELEASE_NOTES.md file.

2019-02-14 20:03 UTC, danmergens approved these changes

2019-02-14 20:03 UTC, merged