Issue #13402 - Fixed assorted bugs in FDCHP data product algorithms
oceanobservatories/ion-functions pull request #12
Opened 2019-06-04 12:49 UTC by sgfoote

Line 796: python expects integers for array indices, so fs=10.0 was causing an error because it made edge = fs * edge_sec a float (see lines 812, 815).
Line 1218: scipy nanmedian was deprecated and removed so it was necessary to change to numpy nanmedian. The scipy version was causing an import error.
Line 12222/12223: If the standard deviation was zero, the mask would be empty. This function is meant to remove spikes, not detect stuck values, and the empty mask was causing an error reshaping the data later in the DPA.
Lines 1497, 1531-1533: In the extreme corner case where the 20 minute sample ("dataset chunk") contains only 1 point of data, no time delta can be computed. The previous logic would compute the delta_time as NaN and then proceed to set the filldata timestamps to NaNs.

2019-06-04 16:56 UTC, danmergens requested changes
Do we have any unit tests for this change?

2019-06-19 15:33 UTC, desiderr commented
Just to make sure, have these newer versions of numpy and scipy already been installed in ion-functions, prior to this pull request?
Thanks.

2019-06-19 16:55 UTC, sgfoote commented
The requirements.py and conda_env.yml file both call out scipy=0.18.1 and numpy=1.12.0 which are the versions I've been testing with. These changes are on hold as I try to debug the unit tests which appear to have broken with the scipy library update. They work with scipy=0.13.3 but fail with scipy=0.14.0, apparently due to updates to the butterworth filter functions in scipy.

2019-08-19 16:28 UTC, tlfish3638 commented
The stream_engine pull request for this ticket was abandoned. After conferring with Seth we decided it would make sense to do the same with this one.

2019-08-19 16:28 UTC, closed without merging