Issue #14537 - Update numpy to 1.16
oceanobservatories/ion-functions pull request #16
Opened 2019-12-09 19:05 UTC by sgfoote

Change-Id: I19e10eed2ca7a03335967d74f75e7a66eedddc0a

2019-12-09 19:19 UTC, tlfish3638 requested changes
Code changes appear reasonable but you need to fix the tests.

2019-12-09 19:39 UTC, sgfoote commented
> Code changes appear reasonable but you need to fix the tests.

The tests pass on my development machine using the ion conda environment (which Travis is also using). Looking at the failures, I see they are all a MemoryError indicating the VM is running out of memory...

2019-12-16 20:21 UTC, steinermg approved these changes

2019-12-17 18:40 UTC, tlfish3638 approved these changes
Thanks for fixing the tests!

2019-12-17 18:41 UTC, merged